baseurl = "http://redesign.noel.fyi"
title = "Noel Miller"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"

[params]
    author = "Noel Miller"
    description = "Noel Miller's Personal Website"
    keywords = "blog,developer,personal,sysadmin,devops,music"
    info = "linux geek | musician | sysadmin"
    avatarurl = "images/avatar.png"
    gravatar = "noelmiller@protonmail.com"
    footercontent = "Disclaimer: Content created on this site is purely my own thoughts and opinions. They do not reflect the views of my employer or any other organization I am a member of."

    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = true
    hideCopyright = true
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# # If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
#     siteID = "ABCDE"
#     # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
#     serverURL = "analytics.example.com"
    
# # If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
#     domain = "example.com"
#     # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
#     serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/Xmas13"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/_noel_miller"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/noel-miller-533909113/"
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 4
    url = "http://redesign.noel.fyi/index.xml"
    rel = "alternate"
    type = "application/rss+xml"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Contact"
            weight = 4
            url = "contact/"


    # [languages.pt-br]
    #     languagename = "Português"
    #     title = "João Ninguém"

    #     [languages.pt-br.params]
    #         author = "João Ninguém"
    #         info = "Full Stack DevOps e Mágico"
    #         description = "Sítio pessoal de João Ninguém"
    #         keywords = "blog,desenvolvedor,pessoal"
    #         footercontent = "Coloque algum texto aqui."

    #     [languages.pt-br.menu]

    #         [[languages.pt-br.menu.main]]
    #         name = "Sobre"
    #         weight = 1
    #         url = "about/"

    #         [[languages.pt-br.menu.main]]
    #         name = "Blog"
    #         weight = 2
    #         url = "posts/"

    #         [[languages.pt-br.menu.main]]
    #         name = "Projetos"
    #         weight = 3
    #         url = "projects/"

    #         [[languages.pt-br.menu.main]]
    #         name = "Contato"
    #         weight = 5
    #         url = "contact/"
